Update collections
VlodShvetsov/Sapientia pull request #1
Opened 2023-05-28 15:25 UTC by VlodShvetsov

2023-05-29 11:59 UTC, OlegDzhuraev commented on Collections/Archetypes/Archetype.cs
> +				/*if (element.entity != entity)
Тут нужно этот коммент оставлять?

2023-05-29 11:59 UTC, OlegDzhuraev commented on Collections/Archetypes/Archetype.cs
> +					OnEntityDestroyEvent.Invoke(ref _elements.Get(valueArray[i].entity.id));
Не совсем нравится идея эмиттить несколько одинаковых ивентов одновременно (с разными значениями), но тут на твоё усмотрение, конечно, это минор)

Я бы попробовал сделать один ивент с массивом или как-то иначе это решить.

2023-05-29 12:00 UTC, OlegDzhuraev requested changes
Changes were requested

2023-05-29 12:06 UTC, VlodShvetsov commented on Collections/Archetypes/Archetype.cs
> +				/*if (element.entity != entity)
Я был не уверен в том, что этот код нужно удалить, т.к. мне казалось что я не предусмотрел что-то.
Сейчас я думаю, что можно удалить, ты прав.

2023-05-29 12:06 UTC, VlodShvetsov commented on Collections/Archetypes/Archetype.cs
> +					OnEntityDestroyEvent.Invoke(ref _elements.Get(valueArray[i].entity.id));
Ты в общем-то прав. Я подумаю над этим.

2023-05-30 10:34 UTC, OlegDzhuraev approved these changes

2023-05-30 10:38 UTC, merged